In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [22]:
df.shape

(569, 33)

In [23]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [24]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
X_train

array([[ 0.58390859,  0.55885402,  0.59457769, ...,  0.28603347,
         0.98914764, -0.423291  ],
       [-0.89080479, -0.35366512, -0.86210949, ..., -0.21239636,
        -0.9776677 , -0.05192629],
       [ 0.15283852, -0.53290995,  0.10133625, ..., -0.52332236,
        -0.70353559, -0.99977977],
       ...,
       [ 0.10746273,  0.54023118,  0.10298176, ...,  0.1529761 ,
         0.22950444, -0.85889787],
       [-0.26405161, -0.1115682 , -0.2372273 , ...,  1.47284399,
         1.68273492,  1.92718278],
       [-0.70930161,  1.24557123, -0.72059568, ..., -0.98412908,
         0.59941765, -0.91581416]])

In [28]:
y_train

132    M
534    B
486    B
504    B
9      M
      ..
217    B
374    B
86     M
47     M
305    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [29]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [30]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,

### Numpy arrays to PyTorch tensors

In [59]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [60]:
X_train_tensor.shape

torch.Size([455, 30])

In [61]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [65]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.linear = nn.Linear(input_dim, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x

  def loss_fn(self, y_pred, y_true):
    loss = nn.BCELoss()
    return loss(y_pred, y_true)

### Important Parameters

In [66]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [67]:
model= MySimpleNN(30)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(epochs):
  y_pred = model(X_train_tensor)
  loss = model.loss_fn(y_pred, y_train_tensor.view(-1,1))
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  print(f'epoch: {epoch}, loss: {loss.item()}')

epoch: 0, loss: 0.6077488660812378
epoch: 1, loss: 0.4871181845664978
epoch: 2, loss: 0.4154888093471527
epoch: 3, loss: 0.3682490885257721
epoch: 4, loss: 0.33455902338027954
epoch: 5, loss: 0.3091251850128174
epoch: 6, loss: 0.2890964448451996
epoch: 7, loss: 0.2728099524974823
epoch: 8, loss: 0.2592315673828125
epoch: 9, loss: 0.24768386781215668
epoch: 10, loss: 0.23770369589328766
epoch: 11, loss: 0.2289629876613617
epoch: 12, loss: 0.2212224155664444
epoch: 13, loss: 0.21430274844169617
epoch: 14, loss: 0.20806695520877838
epoch: 15, loss: 0.20240819454193115
epoch: 16, loss: 0.19724179804325104
epoch: 17, loss: 0.19249968230724335
epoch: 18, loss: 0.18812640011310577
epoch: 19, loss: 0.1840762197971344
epoch: 20, loss: 0.18031109869480133
epoch: 21, loss: 0.17679902911186218
epoch: 22, loss: 0.17351290583610535
epoch: 23, loss: 0.170429527759552
epoch: 24, loss: 0.16752897202968597


### Model 2


In [68]:
import torch
import torch.nn as nn


class Model1(nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.linear1 =nn.Linear(input_dim, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.sigmoid(x)
    return x



In [18]:
class Model2(nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, x):
    x = self.network(x)
    return x

In [10]:
features = torch.rand(10, 5) # create dataset
model1 = Model1(5)
model1(features) # forward pass


tensor([[0.6151],
        [0.6151],
        [0.6151],
        [0.6064],
        [0.6206],
        [0.6151],
        [0.6151],
        [0.6175],
        [0.6151],
        [0.6151]], grad_fn=<SigmoidBackward0>)

In [13]:
model1.linear1.weight

Parameter containing:
tensor([[-0.4327,  0.3711, -0.3119,  0.2425, -0.0013],
        [ 0.1077, -0.3504,  0.1226, -0.3725,  0.1707],
        [-0.1168, -0.2630, -0.2245,  0.2511, -0.2131]], requires_grad=True)

In [14]:
model1.linear2.weight

Parameter containing:
tensor([[ 0.3671, -0.1750, -0.3718]], requires_grad=True)

In [15]:
model1.linear1.bias

Parameter containing:
tensor([ 0.1376, -0.4341,  0.1202], requires_grad=True)

In [16]:
model1.linear2.bias

Parameter containing:
tensor([0.4687], requires_grad=True)

In [17]:
from torchinfo import summary
summary(model1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00